[/]
show-desktop=['<Primary><Alt>d', '<Super>d']
switch-to-workspace-down=['<Control><Alt>Down', '<Super><Alt>Down']
switch-to-workspace-left=['<Super>Page_Up', '<Super><Alt>Left', '<Control><Alt>Left']
switch-to-workspace-right=['<Super>Page_Down', '<Super><Alt>Right', '<Control><Alt>Right']
switch-to-workspace-up=['<Control><Alt>Up', '<Super><Alt>Up']
